### ISSUE TITLE
Package local nicknames not supported in old ASDF

### ISSUE THREAD

**Issue by mtreis86** [phoe/amb#1]
I updated my ASDF to get around this, but the version of ASDF that came with SBCL 2.0.9.55-cd896453c didn't have the package local nicknames features that uiop is requiring, so when I installed AMB at first, it threw this error during quickload.

From the uiop manual "local-nicknames -- If the host implementation supports package local nicknames (check for the :package-local-nicknames feature), then this should be a list of nickname and package name pairs. Using this option will cause an error if the host CL implementation does not support it."

; file: /home/user/common-lisp/amb/src/amb.lisp
; in: UIOP/PACKAGE:DEFINE-PACKAGE #:AMB
;     (UIOP/PACKAGE:DEFINE-PACKAGE #:AMB (:USE #:CL)
;                                  (:LOCAL-NICKNAMES (#:A #:ALEXANDRIA))
;                                  (:EXPORT #:AMB #:CONSTRAIN #:AMB-FAILURE
;                                   #:AMB-FAILURE-STACK))
; 
; caught ERROR:
;   (during macroexpansion of (UIOP/PACKAGE:DEFINE-PACKAGE #:AMB ...))
;   unrecognized define-package keyword :LOCAL-NICKNAMES
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

**Comment by phoe** [comment]
A "proper" way would be indeed to upgrade ASDF/UIOP, but it isn't available for everyone. I fell back to plain old `defpackage` - let me know if that's better now.
